### 회원 가입
POST localhost:8080/api/v1/auth/signup/student
Content-Type: application/json

{
  "email": "seolim8203@naver.com",
  "password": "password123!",
  "name": "테스트학생"
}

### 이메일 인증코드 발송
POST localhost:8080/api/v1/auth/email/send
Content-Type: application/json

{
  "email": "seolim8203@naver.com"
}

### 이메일 인증코드 값 인증
POST localhost:8080/api/v1/auth/email/verify
Content-Type: application/json

{
  "email": "seolim8203@naver.com",
  "code": ""
}

### 로그인
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "student1@momo.city",
  "password": "password123"
}


> {%
    // 🔴 로그인 성공 시 나오는 accessToken을 인텔리제이 메모리에 'auth_token'이라는 이름으로 자동 저장!
    client.global.set("auth_token", response.body.data.accessToken);
%}

### 내 친구 목록
GET localhost:8080/api/v1/friends
Authorization: Bearer {{auth_token}}

### 사용자 검색
GET localhost:8080/api/v1/friends/find?nickname=자
Authorization: Bearer {{auth_token}}

### 친구 요청: 1번 유저에게 친구 요청 -> notification 행 추가
POST localhost:8080/api/v1/friends/request/5
Authorization: Bearer {{auth_token}}

### 수강신청 후 친구 자동 추가
POST http://localhost:8080/api/v1/lectures/2/enrollments
Authorization: Bearer {{auth_token}}

### 친구 요청 철회 -> notifcation 행 삭제
DELETE localhost:8080/api/v1/friends/request/1
Authorization: Bearer {{auth_token}}

### 보낸 친구 요청 목록
GET localhost:8080/api/v1/friends/sent
Authorization: Bearer {{auth_token}}

### 친구 요청 수락(7번이 1번의 요청 수락)
PATCH localhost:8080/api/v1/friends/received/1/accept
Authorization: Bearer {{auth_token}}

### 친구 요청 거절(7번이 1번의 요청 거절)
DELETE localhost:8080/api/v1/friends/received/1/reject
Authorization: Bearer {{auth_token}}

### 받은 친구 요청 목록
GET localhost:8080/api/v1/friends/received
Authorization: Bearer {{auth_token}}

### 친구 차단
PATCH localhost:8080/api/v1/friends/block/1
Authorization: Bearer {{auth_token}}

### 차단한 목록
GET localhost:8080/api/v1/friends/blocked
Authorization: Bearer {{auth_token}}

### 친구 차단 해제
PATCH localhost:8080/api/v1/friends/unblock/1
Authorization: Bearer {{auth_token}}

### 친구 삭제
DELETE localhost:8080/api/v1/friends/delete/1
Authorization: Bearer {{auth_token}}