### 회원 가입
POST localhost:8080/api/v1/auth/signup/student
Content-Type: application/json

{
  "email": "seolim8203@naver.com",
  "password": "password123!",
  "name": "테스트학생"
}

### 이메일 인증코드 발송
POST localhost:8080/api/v1/auth/email/send
Content-Type: application/json

{
  "email": "seolim8203@naver.com"
}

### 이메일 인증코드 값 인증
POST localhost:8080/api/v1/auth/email/verify
Content-Type: application/json

{
  "email": "seolim8203@naver.com",
  "code": "993239"
}

### 로그인
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email" : "student1@momo.city",
  "password": "password123"
}

> {%
    client.global.set("auth_token", response.body.data.accessToken);
%}

### 메시지 친구 목록(채팅 목록)
GET localhost:8080/api/v1/messages/rooms
Authorization: Bearer {{auth_token}}

### 채팅방 조회 및 개설
POST localhost:8080/api/v1/messages/chatrooms/create/1
Authorization: Bearer {{auth_token}}

### 메시지 전송
POST localhost:8080/api/v1/messages/send/20
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "content" : "안뇽"
}

### 메시지 읽음 처리
PATCH localhost:8080/api/v1/messages/read/10
Authorization: Bearer {{auth_token}}

### 메시지 내역 조회(20개씩)-최초 진입
GET localhost:8080/api/v1/messages/history/8
Authorization: Bearer {{auth_token}}

### 메시지 내역 조회(20개씩)-스크롤
GET localhost:8080/api/v1/messages/history/2?lastMessageId=4
Authorization: Bearer {{auth_token}}

### 채팅방 나가기
DELETE localhost:8080/api/v1/messages/chatRooms/leave/1
Authorization: Bearer {{auth_token}}